# Generated by Django 3.1.5 on 2021-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0008_auto_20210422_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltc_tracking',
            name='admin_remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ltc_tracking',
            name='designations',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cpda_application',
            name='pf_number',
            field=models.CharField(default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ltc_tracking',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
